### ISSUE TITLE
Bug: Email Composer will not open

### ISSUE THREAD

**Issue by nehero** [driftyco/ng-cordova#1178]
Tested on Nexus 5 running Android 5.1.1

Followed the exact steps from the ngcordova docs:

`cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git`

And then in a controller

```javascript
.controller('TestCtrl', function($cordovaEmailComposer) {
  var vm = this;

  vm.open = function() {
    document.addEventListener('deviceready', function () {
      $cordovaEmailComposer.isAvailable().then(function() {
  			var email = {
  		    to: '',
  	      cc: '',
  		    bcc: [],
  		    attachments: [],
  		    subject: 'Spray Record Data',
  		    body: 'Data collected from the Spray Record app'
  		  };

  		 $cordovaEmailComposer.open(email).then(null, function () {
  		   alert('Email cancelled');
  		 });
  		}, function () {
  			alert('You do not have an email client set up.');
  		});
    }, false);
  }
});
```

And a button in the html that triggers that function. All that gets called is 'You do not have an email set up'.

If I take out the `$cordovaEmailComposer.isAvailable()` it still doesn't work. 

Not too sure what's going on here.

**Comment by viktorlorentz** [comment]
Seems to be an issue wit the new plugin version (0.8.3).
I fixed it by reverting to 0.8.2.
`cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2`

**Comment by nehero** [comment]
Yup that did the trick. Thanks @viktorlorentz. 

Not going to close as it's obviously still an issue with the current release, unless this should be posted to the repo of the plugin instead of ng-cordova.

**Comment by CheetahDev** [comment]
+1

**Comment by yadavgn** [comment]
+1, 
I have tried this on Android 5.1
plugin version 0.8.3 didn't worked but version 0.8.2 works fine.

**Comment by micschk** [comment]
+1

**Comment by linkchiu** [comment]
+1 Thank you. meet the exactly same problem. In android,  0.8.3 didn't worked but  0.8.2 works fine.

**Comment by bennettstuart** [comment]
Probably a silly question but...

I've just removed version 0.8.3, how do I get the previous 0.8.2?

I tried:
`$ cordova plugin add cordova-plugin-email-composer@0.8.2
Fetching plugin "cordova-plugin-email-composer@0.8.2" via npm
Error: Failed to fetch plugin cordova-plugin-email-composer@0.8.2 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: version not found: cordova-plugin-email-composer@0.8.2`

**Comment by linkchiu** [comment]
Try  the full URL to see how's go. 
cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2

**Comment by bennettstuart** [comment]
@linkchiu Thanks, worked perfectly.

**Comment by nehero** [comment]
@bennettstuart Have you properly included ng-cordova? Try making sure the plugin is fully deleted, then reinstall. Also try deleting your whole android build and rebuilding.

It's sad that @driftyco isn't paying much attention to ionic 1.x now that 2 is out :(

**Comment by bennettstuart** [comment]
I started a fresh project, and reinstalled the things you suggested @nehero.
Everything is working fine now. Thanks for your help!

**Comment by CheetahDev** [comment]
Any update on the topic?
Still not working with 0.8.3

Thanks!

**Comment by CheetahDev** [comment]
Latest plugin version has been published on NPM (0.8.7). Works as expected. :+1:

**Comment by FlawaCLV** [comment]
Still not working for me...

**@ionic-native/core: 4.4.0**
**@ionic-native/email-composer: 4.5.3**
**cordova-plugin-email-composer: 0.8.15**

Any idea?
